development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://h:p42149fb20ab6b59eaca9cf9f4e6ef9ae4f63e8c5c6d6205fdbf54d59aac6ada2@ec2-3-86-75-248.compute-1.amazonaws.com:25349
  channel_prefix: message_me_production
